name = "asistances-backend"
compatibility_date = "2025-10-25"
main = "index.js"
type = "javascript"

# Bindings: conectar D1
[[d1_databases]]
binding = "D1"          # Nombre que usarÃ¡s en env.D1
database_name = "attendance"
